apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-demo
spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: cd-demo

  template:
    metadata:
      labels:
        app: cd-demo

    spec:
      containers:
        - name: cd-demo
          image: nik84810/cd-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80